
services:

  db:
    image: mongo:latest
    container_name: db
    ports:
      - "27018:27017"
    volumes:
      - proiect-chestionare-db:/data/db

    networks:
      - proiect-chestionare

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"

    environment:
      - DB_ADDRESS=mongodb://db:27017

    depends_on:
      - db

    networks:
      - proiect-chestionare


networks:
  proiect-chestionare:
    driver: bridge
    external: true

volumes:
  proiect-chestionare-db: # folosit la baza de date
