// Generated by ts-to-zod
import { z } from "zod";

export const answerSchema = z.object({
    type: z.union([z.literal("grid"), z.literal("text")])
});

export const gridAnswerSchema = answerSchema.extend({
    type: z.literal("grid"),
    choices: z.array(z.number())
});

export const textAnswerSchema = answerSchema.extend({
    type: z.literal("text"),
    text: z.string()
});

export const submissionSchema = z.object({
    answers: z.array(z.union([gridAnswerSchema, textAnswerSchema]))
});

export const formQuestionSchema = z.object({
    text: z.string(),
    type: z.union([z.literal("text"), z.literal("grid")]),
    isOptional: z.boolean()
});

export const gridQuestionSchema = formQuestionSchema.extend({
    isMultipleChoice: z.boolean(),
    type: z.literal("grid"),
    choices: z.array(z.string())
});

export const textQuestionSchema = formQuestionSchema.extend({
    maxChars: z.number(),
    type: z.literal("text")
});

export const formInfoSchema = z.object({
    name: z.string(),
    id: z.string(),
    questions: z.array(z.union([textQuestionSchema, gridQuestionSchema])),
    dateCreated: z.coerce.date().nullable(),
    datePublished: z.coerce.date().nullable(),
    dateClosed: z.coerce.date().nullable(),
    submissions: z.array(submissionSchema).nullable()
});

export const minimalFormInfoSchema = z.object({
    name: z.string(),
    id: z.string(),
    dateCreated: z.coerce.date().nullable(),
    datePublished: z.coerce.date().nullable(),
    dateClosed: z.coerce.date().nullable(),
    submissionsCount: z.number()
});

export const newFormSchema = z.object({
    name: z.string(),
    questions: z.array(z.union([textQuestionSchema, gridQuestionSchema]))
});
