// Generated by ts-to-zod
import { z } from "zod";

export const gridAnswerSchema = z.object({
    choices: z.array(z.number())
});

export const textAnswerSchema = z.object({
    text: z.string()
});

export const submissionSchema = z.object({
    answers: z.array(z.union([gridAnswerSchema, textAnswerSchema]))
});

export const formQuestionSchema = z.object({
    text: z.string(),
    isOptional: z.boolean()
});

export const gridQuestionSchema = formQuestionSchema.extend({
    isMultipleChoice: z.boolean(),
    choices: z.array(z.string())
});

export const textQuestionSchema = formQuestionSchema.extend({
    maxChars: z.number()
});

export const formInfoSchema = z.object({
    name: z.string(),
    questions: z.array(z.union([textQuestionSchema, gridQuestionSchema])),
    dateCreated: z.coerce.date().nullable(),
    dateUpdated: z.coerce.date().nullable(),
    submissions: z.array(submissionSchema).nullable()
});